INSERT INTO mys.CLIENT(FST_NAME,LST_NAME,MID_NAME) values('C1','ABC','N');
INSERT INTO mys.CLIENT(FST_NAME,LST_NAME,MID_NAME) values('C2','ABC','N');
INSERT INTO mys.CLIENT(FST_NAME,LST_NAME,MID_NAME) values('C3','ABC','N');

INSERT INTO mys.ADDRESS(STREET_NAME, CITY) values('STREET 1','Bangalore');
INSERT INTO mys.ADDRESS(STREET_NAME, CITY) values('STREET 2','Chennai');
INSERT INTO mys.ADDRESS(STREET_NAME, CITY) values('STREET 3','Bangalore');